# version: '3'

# services:
#   app-static:
#     image: svelte-docker-static

#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: deploy-static
#     port:
#       - 3000:80

version: "3.8"

services:
  nodeserver:
    build:
      context: .
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    restart: unless-stopped
