version: '3'

services:
  app-node:
    image: svelte-docker-node

    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-node
    ports:
      - "5050:5050"

# version: "3.4"

# services:
#   client:
#     image: client
#     restart: on-failure
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     volumes:
#       - ./:/usr/src/app
#       - /usr/src/app/node_modules
#     hostname: web.local
